# Generated by Django 5.2.4 on 2026-05-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
    ]
