# Generated by Django 5.2.4 on 2026-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0006_remove_productvariant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
