# Generated by Django 5.2.4 on 2026-05-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0009_remove_cartitem_product_cartitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_store.productvariant'),
        ),
    ]
