# Generated by Django 5.2.4 on 2026-05-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0010_alter_cartitem_product_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_variant',
        ),
    ]
