# Generated by Django 5.2.4 on 2026-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0016_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
