# Generated by Django 5.2.4 on 2026-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0017_category_background_image_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10),
        ),
    ]
