# Generated by Django 5.2.4 on 2026-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0018_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='+27 12 345 6789', max_length=20),
            preserve_default=False,
        ),
    ]
