# Generated by Django 5.2.4 on 2026-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0019_address_full_name_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='suburb',
            field=models.CharField(default='subs', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_suburb',
            field=models.CharField(default='subs', max_length=100),
            preserve_default=False,
        ),
    ]
