# Generated by Django 5.2.4 on 2026-08-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0020_address_suburb_order_shipping_suburb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_phone',
            new_name='shipping_phone_number',
        ),
    ]
