# Generated by Django 5.2.4 on 2026-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0021_rename_shipping_phone_order_shipping_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
