# Generated by Django 5.2.4 on 2026-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0022_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
