# Generated by Django 5.2.4 on 2026-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0024_alter_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
