# Generated by Django 5.2.4 on 2026-09-09 10:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0026_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='invoices/'),
        ),
    ]
